module.exports = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	DIRECT_MESSAGE: "DIRECT_MESSAGE",
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
	MESSAGE_SENT:"MESSAGE_SENT",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	TYPING:"TYPING",
	VERIFY_USER:"VERIFY_USER",
	GROUP_CHAT:"GROUP_CHAT",
	NEW_CHAT_USER : "NEW_CHAT_USER",
	LOGOUT:"LOGOUT"
}